### ISSUE TITLE
使用ConfigMap存放全局的Gitlab Runner环境变量

### ISSUE THREAD

**Issue by gudaoxuri** [gudaoxuri/dew#65]
# 自定义配置
```
cat <<EOF | kubectl apply -f -
kind: ConfigMap
apiVersion: v1
metadata:
  name: dew-settings
  namespace: devops
data:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2 -Dorg.apache.maven.user-settings=/opt/maven/settings.xml"
  dew_devops_quiet: "true"
  dew_devops_profile: "<...>"
  dew_devops_docker_host: "<...>"
  dew_devops_docker_registry_url: "<...>"
  dew_devops_kube_config: "<...>"
EOF
```

# TBD 修改Runner的运行配置
